# Generated by Django 2.2.7 on 2019-12-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('type', models.CharField(choices=[('AT', 'Aptitude'), ('ST', 'Swot')], max_length=5)),
            ],
        ),
    ]
