# Generated by Django 2.2.7 on 2019-11-30 07:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 11, 30, 7, 59, 43, 500948, tzinfo=utc), editable=False)),
            ],
        ),
    ]
