# Generated by Django 2.2.7 on 2019-12-01 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.BigIntegerField(unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
