# Generated by Django 2.2.7 on 2019-12-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='round_1_call',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='round_2_call',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
