# Generated by Django 2.2.7 on 2019-12-06 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='called_to_room_no',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='called_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interviewee', to=settings.AUTH_USER_MODEL),
        ),
    ]
