# Generated by Django 2.2.7 on 2019-12-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_auto_20191204_0505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='comment',
            new_name='round_1_comment',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='tech_interests',
        ),
        migrations.AddField(
            model_name='candidate',
            name='round_1_call',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='candidate',
            name='round_2_call',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='candidate',
            name='round_2_comment',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='candidate',
            name='round_2_project_completion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='round_2_project_modification',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='candidate',
            name='round_2_project_understanding',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='interests',
            field=models.CharField(max_length=50),
        ),
    ]
