# Generated by Django 2.2.7 on 2019-12-04 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_auto_20191204_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='round_2_project_template',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='candidate.ProjectTemplate'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='round_2_project_modification',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
