# Generated by Django 2.2.7 on 2019-12-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20191208_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='round_2_call',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
