# Generated by Django 2.2.7 on 2019-12-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20191204_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='round_2_comment',
            field=models.TextField(default=None, null=True),
        ),
    ]
