# Generated by Django 2.2.7 on 2019-12-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_auto_20191204_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='round_2_project_completion',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='round_2_project_understanding',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
