# Generated by Django 2.2.7 on 2019-12-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_auto_20191208_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='round_1_call',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='round_2_call',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
