# Generated by Django 2.2.7 on 2019-12-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_auto_20191209_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='called_to_room_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='called_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
