# Generated by Django 2.2.7 on 2019-12-04 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_auto_20191204_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='round_2_project_template',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='candidate.ProjectTemplate'),
        ),
    ]
