# Generated by Django 2.2.7 on 2019-12-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_auto_20191209_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttemplate',
            name='domain',
            field=models.CharField(max_length=100),
        ),
    ]
