# Generated by Django 2.2.7 on 2019-12-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='room_no',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
