# Generated by Django 2.2.7 on 2019-12-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='is_interviewer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='is_moderator',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='room_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
