# Generated by Django 2.2.7 on 2019-12-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_auto_20191206_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='room_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
